version: "3"
services:
  urless-frontend:
    container_name: urless-frontend
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    ports:
      - "5000:5000"
  urless-backend:
    container_name: urless-backend
    build:
      context: ./
      dockerfile: Dockerfile.api
    expose:
      - 8000
  redis:
    container_name: redis
    image: "redis:latest"
    expose:
      - 6379
