version: "3"
services:
  urless-frontend:
    container_name: urless-frontend
    image: alivx/urless:frontend-latest
    network_mode: "host"
    ports:
      - "8081:8081"
  urless-backend:
    container_name: urless-backend
    image: alivx/urless:api-latest
    network_mode: "host"
    ports:
      - "8080:8080"
  redis:
    container_name: redis
    image: "redis:latest"
    network_mode: "host"
    ports:
      - "6379:6379"
