name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the API Docker image
      run: docker build . --file Dockerfile.api --tag urless-api:$(date +%s)
    - name: Build the Frontend Docker image
      run: docker build . --file Dockerfile.frontend --tag urless-frontend:$(date +%s)
